---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - rabbitmq
      - flower
  - name: redis
    run_list:
      - redisio
      - redisio::enable
      - flower
    attributes:
      flower:
        broker: 'redis://localhost:6379/0'
